# Generated by Django 6.0.4 on 2026-04-29 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_file_name', models.CharField(max_length=255)),
                ('source_hash', models.CharField(blank=True, max_length=64)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'chats_import',
            },
        ),
        migrations.CreateModel(
            name='ChatParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(blank=True, max_length=30)),
                ('wa_id', models.CharField(blank=True, max_length=30)),
                ('is_self', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'chats_participant',
            },
        ),
        migrations.CreateModel(
            name='ChatThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('is_group', models.BooleanField(default=True)),
                ('thread_fingerprint', models.CharField(max_length=64, unique=True)),
                ('source_export_name', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'chats_thread',
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_index', models.PositiveIntegerField()),
                ('message_type', models.CharField(choices=[('USER', 'User Message'), ('SYSTEM', 'System Event'), ('MEDIA_PLACEHOLDER', 'Media Placeholder'), ('DELETED', 'Deleted Message'), ('EDITED', 'Edited Message'), ('UNKNOWN', 'Unknown')], default='USER', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('raw_timestamp', models.CharField(blank=True, max_length=30)),
                ('content', models.TextField(blank=True)),
                ('raw_line', models.TextField(blank=True)),
                ('message_fingerprint', models.CharField(max_length=64)),
                ('is_edited', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chat_import', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chats.chatimport')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='chats.chatparticipant')),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chats.chatthread')),
            ],
            options={
                'db_table': 'chats_message',
                'ordering': ['sequence_index'],
            },
        ),
        migrations.AddField(
            model_name='chatparticipant',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='chats.chatthread'),
        ),
        migrations.AddField(
            model_name='chatimport',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imports', to='chats.chatthread'),
        ),
        migrations.CreateModel(
            name='ChatAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('mime_type', models.CharField(blank=True, max_length=120)),
                ('file_extension', models.CharField(blank=True, max_length=20)),
                ('content_bytes', models.BinaryField(blank=True, null=True)),
                ('content_size', models.PositiveBigIntegerField(default=0)),
                ('sha256', models.CharField(blank=True, max_length=64)),
                ('attachment_fingerprint', models.CharField(blank=True, max_length=64)),
                ('caption', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='chats.chatmessage')),
            ],
            options={
                'db_table': 'chats_attachment',
                'constraints': [models.UniqueConstraint(condition=models.Q(('sha256', ''), _negated=True), fields=('message', 'sha256'), name='uq_chats_attachment_sha256_per_message'), models.UniqueConstraint(condition=models.Q(('attachment_fingerprint', ''), _negated=True), fields=('message', 'attachment_fingerprint'), name='uq_chats_attachment_fp_per_message')],
            },
        ),
        migrations.AddConstraint(
            model_name='chatparticipant',
            constraint=models.UniqueConstraint(fields=('chat', 'phone_number', 'display_name'), name='uq_chats_participant_identity_per_chat'),
        ),
        migrations.AddConstraint(
            model_name='chatmessage',
            constraint=models.UniqueConstraint(fields=('chat_import', 'sequence_index'), name='uq_chats_message_sequence_per_import'),
        ),
        migrations.AddConstraint(
            model_name='chatmessage',
            constraint=models.UniqueConstraint(fields=('chat', 'message_fingerprint'), name='uq_chats_message_fingerprint_per_chat'),
        ),
        migrations.AddConstraint(
            model_name='chatimport',
            constraint=models.UniqueConstraint(condition=models.Q(('source_hash', ''), _negated=True), fields=('chat', 'source_hash'), name='uq_chats_import_chat_source_hash'),
        ),
    ]
